### ISSUE TITLE
GitHub information not loading due to rate limiting

### ISSUE THREAD

**Issue by mjovanc** [njord-rs/njord-rs.github.io#14]
It seems to not work with loading the GitHub information due to rate limiting. I tried using both Safari and Firefox. Can you see if there something that might cause this issue and maybe something we can do to avoid this?

![Screenshot 2024-10-24 at 13 17 28](https://github.com/user-attachments/assets/e9e87c6c-6e40-4245-84f3-b1d915c77751)

**Comment by SvMak** [comment]
OK, I'll fix it.

**Comment by SvMak** [comment]
I added json2jsonp service for call GitHub API, that's make cache for 4h and incrase localStorage ttl to 4h PR #16

**Comment by mjovanc** [comment]
Great work SvMak!
